name: cache_client
description: A simple cache client that uses hive.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  hive: ^2.2.3
  path_provider: ^2.1.1

dev_dependencies:
  mocktail: ^1.0.0
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.6
  test: ^1.19.2
  very_good_analysis: ^5.1.0
